### ISSUE TITLE
Error inside a race while calling "river"

### ISSUE THREAD

**Issue by 2colours** [lizmat/Ecosystem#3]
Hello,

I just updated to the latest version of CLI::Ecosystem and Ecosystem and out of curiosity, I tried running `ecosystem river`. Apart from the "header" for the results, I only got an error log that I [have uploaded here](https://github.com/lizmat/Ecosystem/files/10025054/eco-error.txt).

Do you know what can be the cause and how to fix it?
Thanks.

**Comment by lizmat** [comment]
```
A worker in a parallel iteration (hyper or race) initiated here:
  in block  at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/sources/AE90A015D873D18D51465735DE0395D060FD1EEF (Ecosystem) line 547
  in method river at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/sources/AE90A015D873D18D51465735DE0395D060FD1EEF (Ecosystem) line 544
  in sub MAIN at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/sources/450429A8D15BEF088157FFA518B8E02CE578A5FB (CLI::Ecosystem) line 291
  in block <unit> at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/resources/0EC68F82730DBEDC401C9094A521C65C2A737512 line 3
  in sub MAIN at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/bin/ecosystem line 3
  in block <unit> at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/bin/ecosystem line 1

Died at:
    This type cannot unbox to a native string: P6opaque, Map
      in block  at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/sources/AE90A015D873D18D51465735DE0395D060FD1EEF (Ecosystem) line 547
      in method river at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/sources/AE90A015D873D18D51465735DE0395D060FD1EEF (Ecosystem) line 544
      in sub MAIN at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/sources/450429A8D15BEF088157FFA518B8E02CE578A5FB (CLI::Ecosystem) line 291
      in block <unit> at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/resources/0EC68F82730DBEDC401C9094A521C65C2A737512 line 3
      in sub MAIN at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/bin/ecosystem line 3
      in block <unit> at $HOME/.rakubrew/versions/moar-2022.07/share/perl6/site/bin/ecosystem line 1

**Comment by lizmat** [comment]
Thanks for the headsup.  Will look at it tomorrow.

**Comment by lizmat** [comment]
Fixed (well, actually worked around) in new releases of `Ecosystem` and `CLI::Ecosystem`.

Something is introducing bad `depends` in their `META6.json`.  Trying to find out which modules are the offenders.

**Comment by 2colours** [comment]
There were installation problems afterwards and I couldn't try the solution. Now that it works again, I'm still getting errors:

> A worker in a parallel iteration (hyper or race) initiated here:
  in block  at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/sources/736204DEEFF5BE6E071BE9C68600213E04D6887E (Ecosystem) line 547
  in method river at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/sources/736204DEEFF5BE6E071BE9C68600213E04D6887E (Ecosystem) line 544
  in sub MAIN at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/sources/EE5D58C5E755BB57AD9F45A7720052BE33903F5A (CLI::Ecosystem) line 291
  in block <unit> at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/resources/7FA0DABC989D4AAC5360BB9457F90799844DF6B3 line 3
  in sub MAIN at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/bin/ecosystem line 3
  in block <unit> at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/bin/ecosystem line 1

> Died at:
    Cannot unbox a type object (Nil) to a str.
      in block  at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/sources/736204DEEFF5BE6E071BE9C68600213E04D6887E (Ecosystem) line 547
      in method river at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/sources/736204DEEFF5BE6E071BE9C68600213E04D6887E (Ecosystem) line 544
      in sub MAIN at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/sources/EE5D58C5E755BB57AD9F45A7720052BE33903F5A (CLI::Ecosystem) line 291
      in block <unit> at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/resources/7FA0DABC989D4AAC5360BB9457F90799844DF6B3 line 3
      in sub MAIN at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/bin/ecosystem line 3
      in block <unit> at /home/pm1540/.rakubrew/versions/moar-2022.12/install/share/perl6/site/bin/ecosystem line 1

**Comment by lizmat** [comment]
This has been fixed since then
